# Generated by Django 5.0 on 2024-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cep',
            field=models.CharField(help_text='Apenas números.', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(help_text='Apenas números.', max_length=11),
        ),
    ]
