# Generated by Django 5.0 on 2024-02-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_compliment',
            field=models.CharField(blank=True, max_length=30, verbose_name='Complemento'),
        ),
    ]
