# Generated by Django 5.0 on 2024-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_address_compliment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_number',
            field=models.PositiveIntegerField(max_length=5, verbose_name='Número'),
        ),
    ]
