# Generated by Django 5.0 on 2024-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_number',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
    ]
