# Generated by Django 5.0 on 2024-01-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
