# Generated by Django 5.0 on 2024-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_variation_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_marketing_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.FloatField(default=0),
        ),
    ]
