# Generated by Django 5.0 on 2024-01-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_promo_marketing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
