# Generated by Django 5.0 on 2024-01-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_variation_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_marketing_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.FloatField(default=0),
        ),
    ]
