# Generated by Django 5.0 on 2024-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qnt_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
